const cardTypes = {
  SHUFFLE_CARDS: "SHUFFLE_CARDS",
  FLIP_CARD: "FLIP_CARD",
  UNFLIP_CARDS: "UNFLIP_CARDS",
  LOCK_CARDS: "LOCK_CARDS",
  UNLOCK_UNMATCHED_CARDS: "UNLOCK_UNMATCHED_CARDS",
  MATCH_CARDS: "MATCH_CARDS",
};

export { cardTypes };
