const SHUFFLE_CARDS = "SHUFFLE_CARDS";
const FLIP_CARD = "FLIP_CARD";
const LOCK_CARDS = "LOCK_CARDS";
const UNLOCK_UNMATCHED_CARDS = "UNLOCK_UNMATCHED_CARDS";

export { SHUFFLE_CARDS, FLIP_CARD, LOCK_CARDS, UNLOCK_UNMATCHED_CARDS };
